
{
    'name': "Approval-Recruitment",
    'version': '1.0.0',
    'depends': ['base','hr','mail','approvals','hr_recruitment','hr_skills','hr_appraisal','survey','hr_contract_salary'],
    'summary': "Approval-Man Power",
    'author': "Unisas ITBusiness Solutions Private Limited",
    'category': 'Custom',
    'license': 'LGPL-3',
    'data': [
        "security/ir.model.access.csv",
        "security/approval_recruitment.xml",
        "security/separation/separation_security.xml",
        "data/approval_category_data_inherit.xml",
        "data/hr_data_inherit.xml",
        "data/hr_recruitment_data_inherit.xml",
        "data/date_cron.xml",
        "data/mail_template_hr_applicant.xml",
        "data/mail_template_data.xml",
        "views/approval_category_inherit.xml",
        "views/approval_request_inherit.xml",
        "views/hr_job_inherit.xml",
        "views/hr_applicant_inherit.xml",
        "views/hr_appraisal_inherit.xml",
        "views/hr_employee_inherit.xml",
        "views/recruitment_approval_stage.xml",
        "views/hr_department_inherit_views.xml",
        "views/hr_recruitment_stages_views.xml",
        "views/res_company_inherit.xml",
        "views/ls_state_public_holiday.xml",
        "views/employee_configuration/employment_type.xml",
        "views/employee_configuration/entity_name.xml",
        "views/employee_configuration/base_location.xml",
        "views/employee_configuration/deputed_location.xml",
        "views/employee_configuration/band.xml",
        "views/employee_configuration/level.xml",
        "views/employee_configuration/vertical.xml",
        "views/employee_configuration/function.xml",
        "views/employee_configuration/parent_account.xml",
        "views/employee_configuration/account_office_name.xml",
        "views/employee_configuration/region.xml",
        "views/employee_configuration/employee_status.xml",
        "views/employee_configuration/designation.xml",
        "views/employee_configuration/ls_role.xml",
        "views/employee_configuration/source_of_hire.xml",
        "views/employee_configuration/blood_group.xml",
        "views/employee_configuration/account_type.xml",
        "views/employee_configuration/menus.xml",
        "views/separation/initiate_separation.xml",
        "views/separation/device_type.xml",
        "views/separation/item_name.xml",
        "views/separation/payroll_component.xml",
        "views/separation/exit_interview_questions.xml",
        "views/separation/menus.xml",
        "views/policy/company_policy.xml",
        "views/policy/employee_policy.xml",
        "views/policy/menus.xml",
        'views/job_application_form.xml',
        'views/job_template.xml',
        'views/pre_onboarding_template.xml',
        'report/evaluation_report_template.xml',
        'report/evaluation_report.xml',

    ],
    'assets': {
            # 'web.assets_frontend': [
            #     'approval_recruitment/static/src/css/job.css',
            # ],
            'web.assets_frontend': [
                'approval_recruitment/static/src/scss/custom_buttons.scss',
                'approval_recruitment/static/src/js/application_form.js',

            ],
            'web.assets_backend': [
                'approval_recruitment/static/src/scss/custom_buttons.scss',
            ],
        },
    'installable': True,
    'application': True,
}
