from . import employment_type
from . import entity_name
from . import base_location
from . import deputed_location
from . import band
from . import level
from . import vertical
from . import function
from . import parent_account
from . import account_office_name
from . import region
from . import employee_status
from . import designation
from . import ls_role
from . import source_of_hire
from . import blood_group
from . import account_type